### ISSUE TITLE
Can't compile using opam package

### ISSUE THREAD

**Issue by colin-gd** [seliopou/ocaml-d3#19]
In a clean directory I copied rectangle.ml and rectangle.html. Then I wrote a _tags file with the following contents "`<*> : pacakge(js_of_ocaml), package(js_of_ocaml.syntax), package(d3)`" and ran the following command to compile: "`ocamlbuild -use-ocamlfind rectangle.byte`" so as to use js_of_ocaml afterwards. However, trying to compile the ml file with the above instructions raises the following error.
```
$:ocamlbuild -use-ocamlfind rectangle.byte
+ ocamlfind ocamlc -c -package js_of_ocaml -package js_of_ocaml.syntax -package d3 -o rectangle.cmo rectangle.ml
File "rectangle.ml", line 24, characters 30-32:
Error: '##' is not a valid value identifier.
Command exited with code 2.
Compilation unsuccessful after building 2 targets (0 cached) in 00:00:00.
```

Is this expected? ocaml-d3 doesn't seem to provide compiling instructions and I'd like to use it.

**Comment by seliopou** [comment]
Unfortunately this package has fallen behind the times. I just pushed a change that bumps the minimum version of js_of_ocaml to the latest version. Hopefully this will resolve your issues.
