### ISSUE TITLE
React interface

### ISSUE THREAD

**Issue by Drup** [seliopou/ocaml-d3#2]
You expose all the various handlers, do you think you could expose some signal interface ?

**Comment by seliopou** [comment]
The bindings to event handlers were intentionally written to be agnostic to whatever event loop you choose to use. For example, the [TodoMVC example](https://github.com/seliopou/ocaml-d3/blob/master/examples/todo.ml) has two main functions, one that [uses an Lwt_stream.t](https://github.com/seliopou/ocaml-d3/blob/master/examples/todo.ml#L309-L323) and another that [relies on the naked browser event loop](https://github.com/seliopou/ocaml-d3/blob/master/examples/todo.ml#L295-L307). So it is certainly straightforward to write some wrappers that will shove DOM events into a `React.event`, and then translate that into an updated model using `React.S.fold`. Two ways to do that:

``` ocaml
module R : sig
  val click : (Dom_html.mouseEvent, 'a) handler -> ('a, 'a) t * 'a React.event
end = struct
  let click f =
    let event, push = React.E.create () in
    E.click (fun e d i -> push (f e d i)), event
end
```

... or ....

``` ocaml
module R : sig
  val click : ('a React.event -> unit) -> (Dom_html.mouseEvent, 'a) handler -> ('a, 'a) t
end = struct
  let click push f =
    E.click (fun e d i -> push (f e d i))
end
```

And then I suppose `run` could be written to take a `'datum React.signal`.

These are all pretty thin wrappers. Wouldn't be opposed to integrating something like this as a subpackage.

**Comment by Drup** [comment]
That's the easy direction, getting a `React.event` from event. It would be good to have it included (I think the first version is better).

 A more difficult things is the ability to put reactive values into D3 elements transparently. Something of type `'a React.event -> ('a, 'a) t`. We have a similar interface in tyxml and it works _very_ well.

**Comment by seliopou** [comment]
Whoa, you're blowing my mind. How would you synthesize such a value? Though I'm curious about that answer, I think that including such a value would be antithetical to the approach. Loosely speaking, as the library exists currently, it's exposing an applicative interface. If such a value were to exist, it would then become monadic. Loosely speaking.

**Comment by Drup** [comment]
I don't see how it makes things monadic. You still can't create bind.

I made a huge hack which probably violates half d3's invariants, but somehow it works: https://github.com/Drup/ocaml-d3/blob/reactive_hack/examples/rectangle.ml
You should probably not use it like that, but it illustrate the point. Basically I introduced a function `signal`, similar to `int`/`str`, but for a signal. The concept is trivially translatable to work on the data part.

**Comment by Drup** [comment]
Also, the type is clearly not the one I said, it's 

```
(string -> ('a, string) fn -> ('a, 'a) t) -> string -> string signal -> ('a, 'a) t
```

But It allows to implement what I had in mind. I think it would be possible to have the `'a signal -> ('a,'a) t` by making the type `t` much more clever than it is currently, but I'm not sure it's a good idea.

Note that I didn't look if there was a decent way to do all that with the actual d3 API. ;)

**Comment by seliopou** [comment]
Ohhh, I see what you're going for. Let me take a crack at it in a different way and share. brb.

**Comment by seliopou** [comment]
Check out [this modified rectangle example](https://github.com/seliopou/ocaml-d3/blob/0cbcb748acd7413b200e46fdab5290e76986b515/examples/rectangle.ml). There are inlined comments explaining the situation. I made all the layout attributes potentially reactive, even though in your example you only did one. It may look like a bigger change than should be necessary because of that.

**Comment by Drup** [comment]
I see. Isn't that much slower ? You have to recreate the drawing each time.

**Comment by Drup** [comment]
Also, it means you can't have a little bit of reactivity in the middle, you must make your complete data reactive.

**Comment by seliopou** [comment]
It's a lot less slower than you would think due to the fact that D3 by its very nature does a _differential_ update of a DOM subtree, rather than replacing it wholesale. I ran some benchmarks on the TodoMVC example, compared to various other frameworks and [these were the results](https://twitter.com/seliopou/status/647107352127213568). Using `main_lazy` its the second-fastest in the benchmark. Actually even using `main_lwt`, it's still the second-fastest.

Benchmark code can be found [here](https://github.com/matt-esch/mercury-perf), though I haven't done a PR for ocaml-d3 yet.

**Comment by Drup** [comment]
Ok, point well taken. As usual with performances, "shut up and bench". ;)
Those numbers are very impressive (both for d3 and for jsoo's lack of overhead). I would expect Elm to have done much better, considering they have a similar diffing thing. I would be very interested by a benchmark using React (There is version [here](https://github.com/slegrand45/todomvc/tree/js_of_ocaml) but it's probably not optimized).

**Comment by seliopou** [comment]
Closing, as the discussion is a couple years old and has yet to be acted on.
